# Generated by Django 4.0.6 on 2022-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_boutique_image_alter_ngo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
