# Generated by Django 4.0.6 on 2022-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_boutique_image_alter_ngo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='type',
        ),
        migrations.AddField(
            model_name='boutique',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='type',
            field=models.CharField(default='Boutique', max_length=150),
        ),
        migrations.AddField(
            model_name='ngo',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='type_of_ngo',
            field=models.CharField(default='ONG', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
